kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-manager
  namespace: open-cluster-management
  labels:
    app: cluster-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cluster-manager
  template:
    metadata:
      labels:
        app: cluster-manager
    spec:
      serviceAccountName: cluster-manager
      containers:
      - name: nucleus-operator
        image: quay.io/open-cluster-management/nucleus:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/nucleus"
          - "hub"
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 2
