apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:open-cluster-management:{{ .SpokeCoreName }}-work-agent-addition
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:open-cluster-management:{{ .SpokeCoreName }}-work-agent
subjects:
  - kind: ServiceAccount
    name: {{ .SpokeCoreName }}-work-sa
    namespace: {{ .SpokeCoreNamespace }}
