FROM quay.io/bitnami/golang:1.17  AS builder
WORKDIR /go/src/open-cluster-management.io/registration-operator
COPY . .
ENV GO_PACKAGE open-cluster-management.io/registration-operator
RUN make build --warn-undefined-variables

FROM registry.cn-hangzhou.aliyuncs.com/acs/centos:7-base
ENV USER_UID=99

COPY --from=builder /go/src/open-cluster-management.io/registration-operator/registration-operator /

USER ${USER_UID}
