apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .HubCoreName }}-registration-webhook
  namespace: {{ .HubCoreNamespace }}
  labels:
    app: {{ .HubCoreName }}-registration-webhook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .HubCoreName }}-registration-webhook
  template:
    metadata:
      labels:
        app: {{ .HubCoreName }}-registration-webhook
    spec:
      serviceAccountName: {{ .HubCoreName }}-registration-webhook-sa
      containers:
      - name: {{ .HubCoreName }}-registration-webhook-sa
        image: {{ .RegistrationImage }}
        imagePullPolicy: IfNotPresent
        args:
          - "/registration"
          - "webhook"
          - "--secure-port=6443"
          - "--tls-cert-file=/serving-cert/tls.crt"
          - "--tls-private-key-file=/serving-cert/tls.key"
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
        volumeMounts:
        - name: webhook-secret
          mountPath: "/serving-cert"
          readOnly: true
      volumes:
      - name: webhook-secret
        secret:
          secretName: {{ .HubCoreWebhookSecret }}

