kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .HubCoreName }}-registration-controller
  namespace: {{ .HubCoreNamespace }}
  labels:
    app: nucleushub-registration-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nucleushub-registration-controller
  template:
    metadata:
      labels:
        app: nucleushub-registration-controller
    spec:
      serviceAccountName: {{ .HubCoreName }}-registration-controller-sa
      containers:
      - name: hub-registration-controller
        image: {{ .RegistrationImage }}
        imagePullPolicy: IfNotPresent
        args:
          - "/registration"
          - "controller"
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 2
