apiVersion: v1
kind: Service
metadata:
  name: {{ .HubCoreWebhookRegistrationService }}
  namespace: {{ .HubCoreNamespace }}
spec:
  selector:
    app: {{ .HubCoreName }}-registration-webhook
  ports:
  - port: 443
    targetPort: 6443
