apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "nucleus.open-cluster-management.io/v1",
          "kind": "HubCore",
          "metadata": {
            "name": "hub"
          },
          "spec": {
            "registrationImagePullSpec": "quay.io/open-cluster-management/registration"
          }
        }
      ]
    capabilities: Basic Install
  name: nucleus-hub.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: HubCore
      name: hubcores.nucleus.open-cluster-management.io
      version: v1
  displayName: Nucleus Hub
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - namespaces
          - serviceaccounts
          verbs:
          - create
          - get
          - list
          - update
          - watch
          - patch
          - delete
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - ""
          - events.k8s.io
          resources:
          - events
          verbs:
          - create"
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - get
          - list
          - update
          - watch
          - patch
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - rolebindings
          verbs:
          - create
          - get
          - list
          - update
          - watch
          - patch
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - roles
          verbs:
          - create
          - get
          - list
          - update
          - watch
          - patch
          - delete
          - escalate
          - bind
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - get
          - list
          - update
          - watch
          - patch
          - delete
        - apiGroups:
          - nucleus.open-cluster-management.io
          resources:
          - hubcores
          verbs:
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - nucleus.open-cluster-management.io
          resources:
          - hubcores/status
          verbs:
          - update
          - patch
        serviceAccountName: nucleus-hub
      deployments:
      - name: nucleus-hub
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nucleus-hub
          strategy: {}
          template:
            metadata:
              labels:
                app: nucleus-hub
            spec:
              containers:
              - args:
                - /nucleus
                - hub
                image: quay.io/open-cluster-management/nucleus:latest
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8443
                    scheme: HTTPS
                  initialDelaySeconds: 2
                  periodSeconds: 10
                name: nucleus-operator
                readinessProbe:
                  httpGet:
                    path: /healthz
                    port: 8443
                    scheme: HTTPS
                  initialDelaySeconds: 2
                resources: {}
              serviceAccountName: nucleus-hub
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - open-cluster-management
  maintainers:
  - {}
  maturity: alpha
  provider:
    name: open-cluster-management
  version: 0.1.0
