apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nucleus-spoke
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nucleus-spoke
subjects:
- kind: ServiceAccount
  name: nucleus-spoke
  namespace: open-cluster-management
