apiVersion: v1
kind: Secret
metadata:
  name: {{ .ClusterManagerWebhookSecret }}
  namespace: {{ .ClusterManagerNamespace }}
data:
  tls.crt: {{ .RegistrationServingCert }}
  tls.key: {{ .RegistrationServingKey }}
  ca.crt: {{ .RegistrationAPIServiceCABundle }}
type: Opaque
