apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:open-cluster-management:{{ .ClusterManagerName }}-registration-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:open-cluster-management:{{ .ClusterManagerName }}-registration-controller
subjects:
- kind: ServiceAccount
  namespace: {{ .ClusterManagerNamespace }}
  name: {{ .ClusterManagerName }}-registration-controller-sa
