apiVersion: v1
kind: Secret
metadata:
  name: work-webhook-serving-cert
  namespace: open-cluster-management-hub
data:
  tls.crt: {{ .WorkServingCert }}
  tls.key: {{ .WorkServingKey }}
  ca.crt: {{ .WorkAPIServiceCABundle }}
type: Opaque
