apiVersion: v1
kind: Secret
metadata:
  name: registration-webhook-serving-cert
  namespace: open-cluster-management-hub
data:
  tls.crt: {{ .RegistrationServingCert }}
  tls.key: {{ .RegistrationServingKey }}
  ca.crt: {{ .RegistrationAPIServiceCABundle }}
type: Opaque
