apiVersion: v1
kind: Service
metadata:
  name: {{ .ClusterManagerWebhookRegistrationService }}
  namespace: {{ .ClusterManagerNamespace }}
spec:
  selector:
    app: {{ .ClusterManagerName }}-registration-webhook
  ports:
  - port: 443
    targetPort: 6443
